### ISSUE TITLE
naming issue

### ISSUE THREAD

**Issue by rettinghaus** [saw-leipzig/basic.app#46]
It won't work locally, because `config.js` is referenced, but the file is named `config.tpl.js`

**Comment by ukretschmer** [comment]
This is a feature, not a bug and may caused by ea leck of documentation. The file `config.tpl.js` is a template file for the `config.js`, which finally holds the configuration.
So to get the app running, locally or remote, you need to provide a `config.js`, adjusted to your needs and may use `config.tpl.js` as a template for that and copy and rename it to `config.js`
